name: Deploy to docker hub

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/jonasxpx/unijobs-java:1
    - name: Push docker image
      run: |
        echo ${{secrets.CR_PAT}} | docker login ghcr.io -u JonasXPX --password-stdin
        docker push ghcr.io/jonasxpx/unijobs-java:1
