name: Deploy to docker hub

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ JonasXPX-patch-1 ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag jonasxpx/unijobs-java:1
  push:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Push docker image
      run: |
        echo ${{secrets.CR_PAT}} | docker login ghcr.io -u JonasXPX --password-stdin
        docker push jonasxpx/unijobs-java:1
