name: Deploy to docker hub

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag jonasxpx/unijobs-java:1
  push:
    runs-on: ubuntu-latest
    steps:
    - name: Push docker image
      run: docker push jonasxpx/unijobs-java:1
