name: CI
on:
  push:
    branches: [ development, main, master ]
  pull_request:
    branches: [ development ]
env:
  MYSQL_USER: unijobs
  MYSQL_PASSWORD: secret
  MYSQL_DATABASE: unijobs
jobs:
  init-service:
   runs-on: ubuntu-latest
   services:
    mysql:
      image: mysql:8
      ports: 
        - "3306:3306"
   steps:
     - name: 'Clone repository'
       uses: actions/checkout@v1
     - name: 'Running tests'
       run: |
         chmod +x mvnw
         ./mvnw tests
    
